name: EmeraldBosses
main: EmeraldMC\Main
description: "A very customizable Boss plugin"
version: 1.1.0
api:
- 3.0.0
load: POSTWORLD
author: emerald
commands:
  minibosses:
    description: Manage MiniBosses
    usage: "/minibosses <create/delete>"
    permission: minibosses.command
permissions:
  minibosses.command:
    description: "Allows usage of the /minibosses command"
    default: op

